# Generated by Django 3.1.4 on 2021-01-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('subtitle', models.CharField(max_length=300, verbose_name='subtitle')),
                ('image', models.ImageField(upload_to='site/slideshow', verbose_name='image')),
                ('action_title', models.CharField(default='shop now', max_length=20, verbose_name='action title')),
                ('action_url', models.URLField(blank=True, default='', verbose_name='action url')),
            ],
        ),
    ]
