# Generated by Django 3.1.2 on 2020-11-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_time'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
