# Generated by Django 3.1.2 on 2020-12-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201202_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', related_query_name='post_comments', to='blog.post', verbose_name='Post'),
        ),
    ]
